default: &default
  adapter: postgresql
  encoding: unicode
  username: backend
  password: backendPassword
  host: postgres
  port: 5432

development:
  <<: *default
  database: backend_development_postgres

production:
  <<: *default
  database: backend_production_postgres
