default: &default
  adapter: postgresql
  encoding: unicode
  username: backend
  password: backendPassword
  host: postgres
  port: 5432

development:
  <<: *default
  username:
  host: localhost
  database: backend_development_postgres

production:
  <<: *default
  database: backend_production_postgres

cable:
  <<: *default
  database: backend_production_postgres

queue:
  <<: *default
  database: backend_production_postgres

cache:
  <<: *default
  database: backend_production_postgres
