/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutritionistNutritionistIdIndexRouteImport } from './routes/nutritionist/$nutritionistId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionistNutritionistIdIndexRoute =
  NutritionistNutritionistIdIndexRouteImport.update({
    id: '/nutritionist/$nutritionistId/',
    path: '/nutritionist/$nutritionistId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutritionist/$nutritionistId': typeof NutritionistNutritionistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutritionist/$nutritionistId': typeof NutritionistNutritionistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nutritionist/$nutritionistId/': typeof NutritionistNutritionistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nutritionist/$nutritionistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nutritionist/$nutritionistId'
  id: '__root__' | '/' | '/nutritionist/$nutritionistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NutritionistNutritionistIdIndexRoute: typeof NutritionistNutritionistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutritionist/$nutritionistId/': {
      id: '/nutritionist/$nutritionistId/'
      path: '/nutritionist/$nutritionistId'
      fullPath: '/nutritionist/$nutritionistId'
      preLoaderRoute: typeof NutritionistNutritionistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NutritionistNutritionistIdIndexRoute: NutritionistNutritionistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
